- hosts: all
  remote_user: ec2-user
  become: yes
  become_method: sudo
  tasks:
    - name: "install docker"
      yum:
        name: docker
        status: installed
    - name: "install httpd"
      yum:
        name: httpd
        status: installed
    - name: "service start"
      yum:
        name: httpd
        status: started
        enabled: yes      